name: animator
description: "The most common annimations in most projects."
version: 0.0.1
homepage: https://github.com/samirhassan452/flutter-packages
repository: https://github.com/samirhassan452/flutter-packages
issue_tracker: https://github.com/samirhassan452/flutter-packages/issues
documentation: https://github.com/samirhassan452/flutter-packages/tree/main/animator
topics: []

publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  abstractor:
    git:
      url: https://github.com/samirhassan452/flutter-packages.git
      path: abstractor

  # Fancy pre-built animations that can easily be integrated into any Flutter application.
  animations: ^2.0.11
  # An animation package inspired in [Animate.css](https://animate.style/),
  animate_do: ^3.3.4
  # This shimmer animation widget can help you bring simple yet beautiful skeleton loaders to your project with ease.
  shimmer_animation: ^2.1.0+1
  # A Flutter plugin to create views using Concentric Transition Clipper. Useful for onboarding, page transitions, custom clippers, painters etc.
  # concentric_transition: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
