part of '../base.imports.dart';

enum MimeType {
  ai(mime: "application/postscript"),
  asc(mime: "text/plain"),
  atom(mime: "application/atom+xml"),
  bcpio(mime: "application/x-bcpio"),
  bin(mime: "application/octet-stream"),
  bmp(mime: "image/bmp"),
  cdf(mime: "application/x-netcdf"),
  cgm(mime: "image/cgm"),
  // class(mime: "application/octet-stream"),
  cpio(mime: "application/x-cpio"),
  cpt(mime: "application/mac-compactpro"),
  csh(mime: "application/x-csh"),
  css(mime: "text/css"),
  dcr(mime: "application/x-director"),
  dir(mime: "application/x-director"),
  djv(mime: "image/vnd.djvu"),
  djvu(mime: "image/vnd.djvu"),
  dll(mime: "application/octet-stream"),
  dmg(mime: "application/octet-stream"),
  dms(mime: "application/octet-stream"),
  doc(mime: "application/msword"),
  docx(
    mime:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ),
  dotx(
    mime:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
  ),
  docm(mime: "application/vnd.ms-word.document.macroEnabled.12"),
  dotm(mime: "application/vnd.ms-word.template.macroEnabled.12"),
  dtd(mime: "application/xml-dtd"),
  dvi(mime: "application/x-dvi"),
  dxr(mime: "application/x-director"),
  eps(mime: "application/postscript"),
  etx(mime: "text/x-setext"),
  exe(mime: "application/octet-stream"),
  ez(mime: "application/andrew-inset"),
  gif(mime: "image/gif"),
  gram(mime: "application/srgs"),
  grxml(mime: "application/srgs+xml"),
  gtar(mime: "application/x-gtar"),
  hdf(mime: "application/x-hdf"),
  hqx(mime: "application/mac-binhex40"),
  htm(mime: "text/html"),
  html(mime: "text/html"),
  ice(mime: "x-conference/x-cooltalk"),
  ico(mime: "image/x-icon"),
  ics(mime: "text/calendar"),
  ief(mime: "image/ief"),
  ifb(mime: "text/calendar"),
  iges(mime: "model/iges"),
  igs(mime: "model/iges"),
  jnlp(mime: "application/x-java-jnlp-file"),
  jp2(mime: "image/jp2"),
  jpg(mime: "image/jpeg"),
  jpeg(mime: "image/jpeg"),
  js(mime: "application/x-javascript"),
  latex(mime: "application/x-latex"),
  lha(mime: "application/octet-stream"),
  lzh(mime: "application/octet-stream"),
  mac(mime: "image/x-macpaint"),
  man(mime: "application/x-troff-man"),
  mathml(mime: "application/mathml+xml"),
  me(mime: "application/x-troff-me"),
  mesh(mime: "model/mesh"),
  mif(mime: "application/vnd.mif"),
  ms(mime: "application/x-troff-ms"),
  msh(mime: "model/mesh"),
  nc(mime: "application/x-netcdf"),
  oda(mime: "application/oda"),
  ogg(mime: "application/ogg"),
  pbm(mime: "image/x-portable-bitmap"),
  pct(mime: "image/pict"),
  pdb(mime: "chemical/x-pdb"),
  pdf(mime: "application/pdf"),
  pgm(mime: "image/x-portable-graymap"),
  pgn(mime: "application/x-chess-pgn"),
  pic(mime: "image/pict"),
  pict(mime: "image/pict"),
  png(mime: "image/png"),
  pnm(mime: "image/x-portable-anymap"),
  pnt(mime: "image/x-macpaint"),
  pntg(mime: "image/x-macpaint"),
  ppm(mime: "image/x-portable-pixmap"),
  ppt(mime: "application/vnd.ms-powerpoint"),
  pptx(
    mime:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  ),
  potx(
    mime:
        "application/vnd.openxmlformats-officedocument.presentationml.template",
  ),
  ppsx(
    mime:
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
  ),
  ppam(mime: "application/vnd.ms-powerpoint.addin.macroEnabled.12"),
  pptm(mime: "application/vnd.ms-powerpoint.presentation.macroEnabled.12"),
  potm(mime: "application/vnd.ms-powerpoint.template.macroEnabled.12"),
  ppsm(mime: "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"),
  ps(mime: "application/postscript"),
  qti(mime: "image/x-quicktime"),
  qtif(mime: "image/x-quicktime"),
  ras(mime: "image/x-cmu-raster"),
  rdf(mime: "application/rdf+xml"),
  rgb(mime: "image/x-rgb"),
  rm(mime: "application/vnd.rn-realmedia"),
  roff(mime: "application/x-troff"),
  rtf(mime: "text/rtf"),
  rtx(mime: "text/richtext"),
  sgm(mime: "text/sgml"),
  sgml(mime: "text/sgml"),
  sh(mime: "application/x-sh"),
  shar(mime: "application/x-shar"),
  silo(mime: "model/mesh"),
  sit(mime: "application/x-stuffit"),
  skd(mime: "application/x-koan"),
  skm(mime: "application/x-koan"),
  skp(mime: "application/x-koan"),
  skt(mime: "application/x-koan"),
  smi(mime: "application/smil"),
  smil(mime: "application/smil"),
  so(mime: "application/octet-stream"),
  spl(mime: "application/x-futuresplash"),
  src(mime: "application/x-wais-source"),
  sv4cpio(mime: "application/x-sv4cpio"),
  sv4crc(mime: "application/x-sv4crc"),
  svg(mime: "image/svg+xml"),
  swf(mime: "application/x-shockwave-flash"),
  t(mime: "application/x-troff"),
  tar(mime: "application/x-tar"),
  tcl(mime: "application/x-tcl"),
  tex(mime: "application/x-tex"),
  texi(mime: "application/x-texinfo"),
  texinfo(mime: "application/x-texinfo"),
  tif(mime: "image/tiff"),
  tiff(mime: "image/tiff"),
  tr(mime: "application/x-troff"),
  tsv(mime: "text/tab-separated-values"),
  txt(mime: "text/plain"),
  ustar(mime: "application/x-ustar"),
  vcd(mime: "application/x-cdlink"),
  vrml(mime: "model/vrml"),
  vxml(mime: "application/voicexml+xml"),
  wbmp(mime: "image/vnd.wap.wbmp"),
  wbmxl(mime: "application/vnd.wap.wbxml"),
  wml(mime: "text/vnd.wap.wml"),
  wmlc(mime: "application/vnd.wap.wmlc"),
  wmls(mime: "text/vnd.wap.wmlscript"),
  wmlsc(mime: "application/vnd.wap.wmlscriptc"),
  wrl(mime: "model/vrml"),
  xbm(mime: "image/x-xbitmap"),
  xht(mime: "application/xhtml+xml"),
  xhtml(mime: "application/xhtml+xml"),
  xls(mime: "application/vnd.ms-excel"),
  xml(mime: "application/xml"),
  xpm(mime: "image/x-xpixmap"),
  xsl(mime: "application/xml"),
  xlsx(
    mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ),
  xltx(
    mime:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
  ),
  xlsm(mime: "application/vnd.ms-excel.sheet.macroEnabled.12"),
  xltm(mime: "application/vnd.ms-excel.template.macroEnabled.12"),
  xlam(mime: "application/vnd.ms-excel.addin.macroEnabled.12"),
  xlsb(mime: "application/vnd.ms-excel.sheet.binary.macroEnabled.12"),
  xslt(mime: "application/xslt+xml"),
  xul(mime: "application/vnd.mozilla.xul+xml"),
  xwd(mime: "image/x-xwindowdump"),
  xyz(mime: "chemical/x-xyz"),
  zip(mime: "application/zip"),
  ;

  const MimeType({required this.mime});
  final String mime;
}
