name: assetor
description: "A Flutter package which enables you to access assets through variables instead of string."
version: 0.0.1
homepage: https://github.com/samirhassan452/flutter-packages
repository: https://github.com/samirhassan452/flutter-packages
issue_tracker: https://github.com/samirhassan452/flutter-packages/issues
documentation: https://github.com/samirhassan452/flutter-packages/tree/main/assetor
topics: []

publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
  flutter_gen: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# For more info visit: 
# * Package: https://pub.dev/packages/flutter_gen
# * Configuration: [https://github.com/FlutterGen/flutter_gen/blob/main/packages/core/lib/settings/config_default.dart]
# To use flutter_gen:
# *1. Make sure to activate it: [dart pub global activate flutter_gen]
# *2. Run this command: [fluttergen]
flutter_gen:
  # Optional (default: lib/gen/)
  output: lib/src/gen/

  # Optional
  integrations:
    # * Enables you to access svg/lottie assets through variable or svg/lottie widgets.
    # * For more integrations, visit above link for configuration
    # flutter_svg: true # Must install flutter_svg from pub.dev
    # lottie: true  # Must install lottie from pub.dev

  assets:
    # Optional
    enabled: true
    # Optional
    outputs:
      # Set to true if you want this package to be a package dependency
      package_parameter_enabled: true
      class_name: Assetor

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/
    - assets/images/svg/
    - assets/lottie/