name: pixelify
description: "Reach out to different types of Icon/Image widgets in just one place."
version: 0.0.1
homepage: https://github.com/samirhassan452/flutter-packages
repository: https://github.com/samirhassan452/flutter-packages
issue_tracker: https://github.com/samirhassan452/flutter-packages/issues
documentation: https://github.com/samirhassan452/flutter-packages/tree/main/pexelify
topics: []

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  abstractor:
    git:
      url: git@github.com:samirhassan452/flutter-packages.git
      path: abstractor
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
