name: toastify
description: "Toastify is  built on top of Toastification package with more customization and easy access to use."
version: 0.0.1
homepage: https://github.com/samirhassan452/flutter-packages
repository: https://github.com/samirhassan452/flutter-packages
issue_tracker: https://github.com/samirhassan452/flutter-packages/issues
documentation: https://github.com/samirhassan452/flutter-packages/tree/main/toastify
topics: []

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Toastification is a Flutter package that allows you to easily show toast and notification messages in your application.
  toastification: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
