name: c2_abstractor
description: "A widget that enables you to create use-cases for any widget easily."
version: 0.0.1
homepage:
repository:
issue_tracker:
documentation:
topics: []


environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
